//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.01 at 07:57:56 PM GMT 
//


package bias.extension.FinancialFlows.xmlb;

import jakarta.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the bias.extension.FinancialFlows.xmlb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: bias.extension.FinancialFlows.xmlb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RegularFlow }
     * 
     */
    public RegularFlow createRegularFlow() {
        return new RegularFlow();
    }

    /**
     * Create an instance of {@link RegularFlows }
     * 
     */
    public RegularFlows createRegularFlows() {
        return new RegularFlows();
    }

    /**
     * Create an instance of {@link Parts }
     * 
     */
    public Parts createParts() {
        return new Parts();
    }

    /**
     * Create an instance of {@link SingleFlow }
     * 
     */
    public SingleFlow createSingleFlow() {
        return new SingleFlow();
    }

    /**
     * Create an instance of {@link SingleFlows }
     * 
     */
    public SingleFlows createSingleFlows() {
        return new SingleFlows();
    }

}
