//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.04.29 at 08:21:45 PM EEST 
//


package bias.core.pack;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;

/**
 * <p>Java class for pack-type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="pack-type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AppLauncher"/>
 *     &lt;enumeration value="AppCore"/>
 *     &lt;enumeration value="Extension"/>
 *     &lt;enumeration value="Skin"/>
 *     &lt;enumeration value="IconSet"/>
 *     &lt;enumeration value="Library"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum PackType {

    @XmlEnumValue("AppLauncher")
    APP_LAUNCHER("AppLauncher"),
    @XmlEnumValue("AppCore")
    APP_CORE("AppCore"),
    @XmlEnumValue("Extension")
    EXTENSION("Extension"),
    @XmlEnumValue("Skin")
    SKIN("Skin"),
    @XmlEnumValue("IconSet")
    ICON_SET("IconSet"),
    @XmlEnumValue("Library")
    LIBRARY("Library");
    private final String value;

    PackType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PackType fromValue(String v) {
        for (PackType c: PackType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
