//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.04.29 at 08:21:45 PM EEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://bias.sourceforge.net")
package bias.core.pack;
