Daily == Daily
Weekly == Weekly
Monthly == Monthly
Yearly == Yearly
Sunday == Sunday
Monday == Monday
Tuesday == Tuesday
Wednesday == Wednesday
Thursday == Thursday
Friday == Friday
Saturday == Saturday
January == January
February == February
March == March
April == April
May == May
June == June
July == July
August == August
September == September
October == October
November == November
December == December
Minutes == Minutes
Hours == Hours
Days == Days
Title == Title
Date == Date
Time == Time
Filter == Filter
Periodic == Periodic
Add.Reminder == Add Reminder
Delete.Reminder == Delete Reminder
New.Reminder == New Reminder
Done == Done!
remind.next.time == remind next time 
delete.this.reminder == delete this reminder
Remind.again.in == Remind again in...
tooltip.weekly == Every specified day of the week (Sunday is first day)
tooltip.monthly == Every specified day number of the month
tooltip.yearly == Every specified date of the year
