Daily == Ежедневно
Daily.WeekDaysOnly == Ежедневно / только по будням
Daily.WeekEndOnly == Ежедневно / только по выходным
Weekly == Еженедельно
Monthly == Ежемесячно
Quarterly == Ежеквартально
Yearly == Ежегодно
Sunday == Воскресенье
Monday == Понедельник
Tuesday == Вторник
Wednesday == Среда
Thursday == Четверг
Friday == Пятница
Saturday == Субота
January == Январь
February == Февраль
March == Март
April == Апрель
May == Май
June == Июнь
July == Июль
August == Август
September == Сентябрь
October == Октябрь
November == Ноябрь
December == Декабрь
Minutes == Минут
Hours == Часов
Days == Дней
Title == Заголовок
Date == Дата
Time == Время
Filter == Фильтр
Periodic == Периодично
Add.Reminder == Добавить напоминание
Delete.Reminder == Удалить напоминание
New.Reminder == Новое напоминание
Done == Готово!
remind.next.time == напомнить в следующий раз 
delete.this.reminder == удалить это напоминание
Remind.again.in == Напомнить снова через...
tooltip.weekly == Каждый заданный день недели (Воскресенье - первый день)
tooltip.monthly == Каждое заданное число месяца
tooltip.quarterly == Каждое заданное число первого месяца каждого квартала
tooltip.yearly == Каждая заданная дата года
