main.window.title == Bias :: Versatile Information Manager
preferred.language.preference.title == Preferred language (needs Bias restart)
preferred.datetime.format.preference.title == Preferred date-time format
preferred.timeout.preference.title == Preferred timeout for network operations (in seconds)
use.systrayicon.preference.title == Use system tray icon
use.systrayicon.preference.description == Allocates space in system tray and allows to hide/restore application to/from system tray icon
remain.in.systray.on.window.close.preference.title == Remain in system tray when main window closes
start.hidden.preference.title == Hide main window on start (and show system tray icon instead)
minimize.to.systray.preference.title == Minimize main window to system tray
auto.save.on.exit.preference.title == Auto save on exit
display.confirmation.dialogs.preference.title == Display confirmation dialogs
display.confirmation.dialogs.preference.description == Requests user's confirmation on actions like: delete entry, uninstall add-on etc.
enable.auto.update.preference.title == Enable automatic update (requires internet connection)
auto.update.interval.preference.title == Automatic update interval, in days (set to 0 to update on startup only)
show.memory.usage.preference.title == Show memory usage information in status bar
export.info == Note: there're two export modes available:<br/><ul><li>static - only selected nodes will be exported</li><li>dynamic - in addition to nodes selected for static export, collapsed nodes can be selected<br/>to enable recursive export; in this case all nested nodes will be exported as well<br/>(this is especially handy when stored configurations are used)</li></ul>
loaded.ready == loaded & ready
category.added == category '$' added
entry.added == entry '$' added
category.deleted == category '$' deleted
entry.deleted == entry '$' deleted
preferences.applied == preferences applied
export.done == export done
import.done == import done
password.changed == password changed
modified.by == modified by
data.saved == data saved
add.category.to.rootlevel == Add category to the root level
add.entry.to.rootlevel == Add entry to the root level
tabs.placement == Choose tabs placement
icon == Icon
caption == Caption
type == Type
new.category == New category
new.entry == New entry
add.category == add category
add.entry == add entry
no.entry.extensions.installed == There're no entry extensions installed currently.<br/>Entries can't be added before there's at least one entry extension installed.
failed.to.add.category == Failed to add category
failed.to.add.entry == Failed to add entry.<br/>Some entry extension(s) may be broken.<br/>Try to open add-ons management dialog, <br/>and uninstall/reinstall broken extensions.
elapsed.time == elapsed time
estimated.time.left == estimated time left
transfer.type.no.longer.available == It looks like transfer type used by this stored configuration is no longer available (extension uninstalled?)
wrong.password == It seems that password is wrong...
exporting.data == Exporting data
data.export == Data export
export.completed == Data export - Completed
export.success == Data have been successfully exported
export.failed == Failed to export data!
export.failure == Data export - Failed
export.discarded.no.data.changes == Export discarded: data haven't changed since last export
error.details == Error details
importing.data == Importing data
data.import == Data import
import.completed == Data import - Completed
import.success == Data have been successfully imported
import.failed == Failed to import data
import.failure == Data import - Failed
import.discarded.no.data.changes == Import discarded: data haven't changed since last import
change.password == change password
current.password == current password
new.password == new password
new.password.confirmation == confirm new password
change.password.failure == Failed to change password!
change.password.failure.invalid.confirmation == Failed to change password!<br/>New password hasn't been correctly confirmed!
change.password.success == Password has been successfully changed!