app.title == Bias :: Versatile Information Manager
addons.management.title == Bias :: Add-Ons Management
version == Version
username.preference.title == Username
preferred.language.preference.title == Preferred language (needs Bias restart)
preferred.datetime.format.preference.title == Preferred date-time format
preferred.timeout.preference.title == Preferred timeout for network operations (in seconds)
use.systrayicon.preference.title == Use system tray icon
use.systrayicon.preference.description == Allocates space in system tray and allows to hide/restore application to/from system tray icon
remain.in.systray.on.window.close.preference.title == Remain in system tray when main window closes
start.hidden.preference.title == Hide main window on start (and show system tray icon instead)
minimize.to.systray.preference.title == Minimize main window to system tray
auto.save.on.exit.preference.title == Auto save on exit
display.confirmation.dialogs.preference.title == Display confirmation dialogs
display.confirmation.dialogs.preference.description == Requests user's confirmation on actions like: delete entry, uninstall add-on etc.
auto.mode.preference.title == Enable auto-mode
auto.mode.preference.description == Allows to perform some common actions (like saving data before export) in automatic mode (without user's confirmation)
enable.auto.update.preference.title == Enable automatic update (requires internet connection)
auto.update.interval.preference.title == Automatic update interval, in days (set to 0 to update on startup only)
show.memory.usage.preference.title == Show memory usage information in status bar
export.info == Note: there're two export modes available:<br/><ul><li>static - only selected nodes will be exported</li><li>dynamic - in addition to nodes selected for static export, collapsed nodes can be selected<br/>to enable recursive export; in this case all nested nodes will be exported as well<br/>(this is especially handy when stored configurations are used)</li></ul>
loaded.ready == loaded & ready
category.added == category '$' added
entry.added == entry '$' added
category.deleted == category '$' deleted
entry.deleted == entry '$' deleted
preferences.applied == preferences applied
export.done == export done
import.done == import done
password.changed == password changed
modified.by == modified by
data.saved == data saved
data.saving == saving data...
error.message.data.collect.failure == Failed to collect data!
error.message.toolsdata.collect.failure == Failed to collect tools data!
error.message.data.save.failure == Failed to save data!
add.category.to.rootlevel == Add category to the root level
add.entry.to.rootlevel == Add entry to the root level
tabs.placement == Choose tabs placement
icon == Icon
caption == Caption
type == Type
add.category == Add category
add.entry == Add entry
configure.category == Configure category
active.category.tabs.placement == Active category tabs placement
root.category.tabs.placement == Root category tabs placement
category.configuration.error == Failed to set category properties!
entry.location == Entry location (will be moved on change)
configure.entry == Configure entry
entry.configuration.error == Failed to configure/apply/store entry settings!
relocate.entry.or.category == Relocate entry/category
relocate.failed == Failed to relocate entry/category
no.entry.extensions.installed == There're no entry extensions installed currently.<br/>Entries can't be added before there's at least one entry extension installed.
add.category.failure == Failed to add category
add.entry.failure == Failed to add entry.<br/>Some entry extension(s) may be broken.<br/>Try to open add-ons management dialog, <br/>and uninstall/reinstall broken extensions.
elapsed.time == elapsed time
estimated.time.left == estimated time left
transfer.type.no.longer.available == It looks like transfer type used by this stored configuration is no longer available (extension uninstalled?)
wrong.password == It seems that password is wrong...
exporting.data == Exporting data
data.export == Data export
export.completed == Data export - Completed
export.success == Data have been successfully exported
export.failure == Data export failed!
error.details == Error details
importing.data == Importing data
data.import == Data import
import.completed == Data import - Completed
import.success == Data have been successfully imported
import.failure == Data import failed!
change.password == Change password
current.password == Current password
new.password == New password
password.confirmation == Confirm password
password.confirmation.failure == Password hasn't been correctly confirmed!
change.password.success == Password has been successfully changed!
change.password.failure == Failed to change password!
delete.active.entry.or.category == Delete active entry/category
delete.active.entry.or.category.failure == Failed to delete entry/category!
delete == Delete
rename == Rename
save == Save
new.name == New name
overwrite.existing == Overwrite existing
update.installed == Update installed
error == Error
information == Information
export.save.data.title == Save data before export
export.save.data.message == Data have to be saved before export. Save now and continue?
export.preferences == Export preferences
export.data.entry.configs == Export data entry configs
export.data.entry.configs.related.only == Export data entry configs related to exported data entries only
export.tools.data == Export tools data
export.icons == Export icons
export.icons.related.only == Export icons related to exported data entries only
export.app.core == Export application core
export.addons.and.libs == Export addons and libraries
export.addon.configs == Export addon configs
export.import.export.configs == Export stored import/export configurations
export.use.password == Encrypt exported data using password
export.data.compressing == Compressing data to be exported...
export.data.compressed == Data to be exported have been successfully compressed.
import.data.entries == Import data entries
import.data.entry.configs == Import data entry configs
import.preferences == Import preferences
import.tools.data == Import tools data
import.icons == Import icons
import.and.update.app.core == Import and update application core
import.addons.and.libs == Import addons and libraries
import.addon.configs == Import addon configs
import.import.export.configs == Import import/export cofigs
import.use.password == Decrypt imported data using password
import.data.extracting == Extracting data to be imported...
import.data.extracted == Data to be imported have been successfully extracted
import.failure.no.data.retrieved == Import source initialization failure: no data have been retrieved!
import.data.retrieved == Data to be imported successfully retrieved
transfer.configuration.select == Select stored configuration to use, <br/>or leave selection empty and press OK to start custom trasfer
transfer.type == Transfer type
transfer.options.missing.error == Transfer options are missing!
transfer.file.location.missing.error == Transfer file location is missing!
transfer.force == Force transfer even if data haven't been changed since last transfer
transfer.data.transferring == Data is being transferred...
transfer.configuration.delete.failure == Failed to delete selected transfer configuration!
transfer.configuration.rename.failure == Failed to rename selected transfer configuration!
transfer.configuration.save == If you want to save this transfer configuration,<br/> input a name for it (or select existing one to overwrite)
transfer.configuration.saved == Transfer configuration saved as '$'
transfer.discarded.no.data.changes == Transfer discarded: data haven't changed since last transfer
password.confirmation.invalid == [INVALID]
password.confirmation.confirmed == [CONFIRMED]
confirmation.delete.title == Delete confirmation
confirmation.delete.message == Are you sure you want to delete active entry?
confirmation.uninstall.title == Uninstall confirmation
confirmation.uninstall.message == Are you sure you want to uninstall selected add-ons?
confirmation.disable.note == Note: this dialog can be disabled via preferences option<br/>
info.message.launcher.updated == Important! Bias launcher has been updated.<br/>Though, such update can not be applied automatically.<br/>To apply it, you have to shutdown Bias, replace <b><i>bias.jar<i></b> file with <b><i>update_bias.jar<i></b> (in working directory) and then start Bias again.
info.message.auto.update.complete == Automatic update complete
auto.update.disable.note == Note: automatic update can be disabled<br/>via preferences option 'Enable automatic update'
auto.update.adjust.interval.note == Note:update interval can be adjusted via preferences option 'Automatic update interval'
info.message.restart.to.apply.changes == Bias should be restarted to changes take effect
info.message.entry.extension.first.usage == This is first time you use '$' entry extension.<br>Please, configure extension's default settings...
error.message.extension.settings.serialization.failure == Extension <i>$</i> failed to serialize settings!<br/>Settings that have failed to serialize will be lost! :(<br/>This the most likely is an extension's bug or 3rd-party library dependency problem.<br/>You can either:<br/><ul><li>check for new version of extension (the bug may be fixed in new version)</li><li>check whether all 3rd-party libraries extension depends on are installed</li><li>uninstall extension to avoid further instability and data loss</li><li>contact extension's author for further help</li></ul>
error.message.extension.data.serialization.failure == Extension <i>$</i> failed to serialize data!<br/>Settings that have failed to serialize will be lost! :(<br/>This the most likely is an extension's bug or 3rd-party library dependency problem.<br/>You can either:<br/><ul><li>check for new version of extension (the bug may be fixed in new version)</li><li>check whether all 3rd-party libraries extension depends on are installed</li><li>uninstall extension to avoid further instability and data loss</li><li>contact extension's author for further help</li></ul>
error.message.tools.initialization.failure == Failed to initialize tools!
error.message.tool.initialization.failure == Failed to initialize tool '$'!
error.message.transferrers.initialization.failure == Failed to initialize transferrers!
error.message.transferrer.initialization.failure == Failed to initialize transferrer '$'!
error.message.entryextension.initialization.failure == Failed to initialize entry-extension!
error.message.data.representation.failure == Failure detected while representing data!
error.message.preferences.load.failure == Failed to load preferences!
error.message.preferences.save.failure == Failed to save preferences!
warning.message.preferences.contain.error == Preference configuration contains error(s)! Preferences won't be saved, until that is fixed.
default.skin == Default Skin
default.skin.description == Default native Java cross-platform Skin.
error.message.skin.initialization.failure == Skin '$' failed to initialize!
info.message.extension.does.not.provide.detailed.info == Detailed information is not provided with this extension
error.message.extension.details.display.failure == Failed to display extension's details!
info.message.skin.does.not.provide.detailed.info == Detailed information is not provided with this skin
error.message.skin.details.display.failure == Failed to display skin's details!
info.message.iconset.does.not.provide.detailed.info == Detailed information is not provided with this icon-set
error.message.iconset.details.display.failure == Failed to display icon-set's details!
info.message.library.does.not.provide.detailed.info == Detailed information is not provided with this library
error.message.library.details.display.failure == Failed to display library's details!
error.message.invalid.url == Invalid URL!
messages.history == Messages History
choose.placement == Choose placement
info.message.entry.not.configurable == Selected entry is not configurable!
info.message.entry.not.configurable.details == (appropriate entry-extension does not provide configuration option)
relocated.item == Relocated item
target.category == Target category
show.all.packages == Show all packages (includes already installed packages with the same or older version into the list)
show.active.downloads == Show active downloads
confirmation.cancel.active.downloads == Cancel active downloads confirmation
confirmation.exit.unsaved.changes.message == All unsaved changes will be lost.
confirmation.exit == Are you sure you want to exit?
exit.confirmation == Exit confirmation
exit.confirmation.active.downloads.present == Some downloads are still in progress. Are you sure you want to cancel all active downloads and exit?
save.changes.before.exit == Save changes before exit
exit == Exit
about.bias == About Bias
manage.addons == Manage add-ons
preferences == Preferences
add.or.install == Add/Install
download.and.install == Download/install
install.or.update == Install/Update
uninstall == Uninstall
error.message.extensions.uninstall.failure == Failed to uninstall extension(s)!
error.message.skins.uninstall.failure == Failed to uninstall skin(s)!
error.message.iconsets.uninstall.failure == Failed to uninstall icon-set(s)!
error.message.icons.remove.failure == Failed to remove icon(s)!
error.message.icons.install.failure == Failed to install icons!
remove.selected.icons == Remove selected icon(s)
uninstall.selected.iconsets == Uninstall selected icon-set(s)
configure == Configure
info.message.extension.is.not.yet.configurable == This extension can not be (re)configured yet.
reactivate.skin == (Re)Activate skin
info.message.skin.is.not.yet.activable == This Skin can not be activated yet.
error.message.skin.reactivation.failure == Failed to (re)activate Skin!
info.message.restart.bias.first == Restart Bias first.
warning.message.nothing.to.install == Nothing to install!
success.message.icons.installed == Icons successfully installed!
details == Details
history.back.to.first == Back to first
history.back == Back
history.forward == Forward
history.forward.to.last == Forward to last
running.tasks.wait == Some tasks are still running, please wait for them to finish...
running.tasks.force.exit == Force exit (all incomplete tasks will be aborted)
error.data.load.failure == Failed to load data!
memory.usage == Memory Usage: $ of $ Mb
info.message.icons.installation == installing icons...
info.message.packages.installation == installing packages...
info.message.local.packages.installation == installing local packages...
error.message.dependency.resolution.failure == Failed to resolve dependency for package '$'! Following dependency-package is not available: $ '$' $.
error.message.dependencies.handle.resolve.failure == Failed to handle/resolve dependencies!
version.x.or.higher == version $ or higher
refresh == Refresh
error.message.pack.details.page.load.failure == Failed to load package details page!
error.message.repository.url.resolution.failure == Failed to resolve repository URL!
select.all.updates == Select all updates
cancel.download.and.installation == Cancel download/installation
filter == Filter
extensions == Extensions
skins == Skins
icons == Icons
online == Online
registered.libraries == Registered libraries
clean.unused.data.and.config.files == Clean unused data and config files
info.message.clean.unused.data.and.config.files == NOTE: This operation will remove all unused data and configuration files that were used by addons that are not currently loaded<br>(Do that only if you don't plan to install these addons again or want to reset their data/settings)
done == Done
detect.unused.libraries == Detect unused libraries
uninstall.unused.libraries == Uninstall unused libraries!
info.message.uninstall.unused.libraries == NOTE: uninstallation of unused libriaries will remove all libraries that some not currently loaded addons were dependent on<br>(Do that only if you don't plan to install these addons again)
error.message.unused.libraries.detection.failure == Failed to detect unused librarires!
error.message.unused.libraries.uninstall.failure == Failed to uninstall unused librarires!
advanced.options == Advanced options
error.message.addons.management.screen.initialization.failure == Failed to initialize add-ons management screen!
error.message.addon.info.read.from.file.failure == Failed to read add-on's info from file
name == Name
version == Version
author == Author
description == Description
status == Status
type == Type
size == Size
AddOnStatusImported == [Imported] (restart needed)
AddOnStatusInstalled == [Installed] (restart needed)
AddOnStatusUpdated == [Updated] (restart needed)
AddOnStatusLoaded == [Loaded]
AddOnStatusNew == [New]
AddOnStatusUpdate == [Update]
AddOnStatusUnused == [Unused]
AddOnStatusBroken == [Broken]
AddOnStatusBrokenDependencies == [Broken dependencies]
AddOnStatusRegisteredInstalled == [Registered/installed]
AddOnStatusNotRegisteredInstalled == [Not registered/installed]
info.message.refreshing.online.packages.list == refreshing online packages list...
error.message.packages.list.parse.failure == Failed to parse list of available packages!
error.message.packages.list.retrieve.failure == Failed to retrieve list of available addons!
info.message.packages.list.refresh.canceled.by.user == Packages list refresh canceled by user!
info.message.downloading.and.installing.packages == downloading/installing packages...
success.message.addon.installed == Add-On '$ $' has been successfully installed!
error.message.addon.installation.failure == Failed to install add-on '$ $'!
success.message.package.downloaded.and.installed == $ '$ $' - successfully downloaded/installed!
error.message.package.download.or.installation.failure == $ '$ $' - failed to download/install!
error.message.failed.to.retrieve.package == Failed to retrieve package!
info.message.package.download.and.installation.canceled.by.user == Downloading/installation of package '$ $' has been canceled by user!
info.message.packages.download.and.installation.canceled.by.user == Packages downloading/installation canceled by user!
addons.installation.confirmation == Add-Ons Installation Confirmation
addon.dependencies == AddOn dependencies
addon.has.no.dependencies == AddOn has no dependencies
applauncher == Application launcher
appcore == Application core
extension == Extension
skin == Skin
iconset == Icon-set
library == Library