main.window.title == Bias :: Многофункциональный информационный менеджер
preferred.language.preference.title == Предпочитаемый язык (требует перезагрузки Bias)
preferred.datetime.format.preference.title == Предпочитаемый формат даты/времени
preferred.timeout.preference.title == Предпочитаемый таймаут для сетевых операций (в секундах)
use.systrayicon.preference.title == Использовать значок в системном лотке
use.systrayicon.preference.description == Резервирует место в системном лотке и разрешает прятать/восстанавливать приложение при помощи значка
remain.in.systray.on.window.close.preference.title == Оставаться в системном лотке при закрытии основного окна
start.hidden.preference.title == Прятать основное окно при старте
minimize.to.systray.preference.title == Сворачивать основное окно в системный лоток
auto.save.on.exit.preference.title == Автоматическое сохранение при выходе
display.confirmation.dialogs.preference.title == Показывать подтверждающие диалоги
display.confirmation.dialogs.preference.description == Запрашивает подтверждение пользователя при действиях наподобие удаления записи, деинсталляции расширения и т.п.
enable.auto.update.preference.title == Разрешить автоматическое обновление (требует подключения к интернет)
auto.update.interval.preference.title == Интервал автоматического обновления, в днях (выставить на 0 для обновления только при старте)
show.memory.usage.preference.title == Показывать информацию о использовании памяти в строке состояния
export.info == Заметка: доступны два режима експорта:<br/><ul><li>статический - только выделенные елементы будут экпортированны</li><li>динамический - в дополнение к статически экспортируемым елементам, могут быть выбраны свернутые елементы (категории)<br/>для задействования динамического экспорта; в этом случае все вложенные елементы также будут экспортированны<br/>(это особенно удобно при использовании хранимых экспорт-конфигураций)</li></ul>
loaded.ready == загружен, готов к работе
category.added == категория '$' добавлена
entry.added == запись '$' добавлена
category.deleted == категория '$' удалена
entry.deleted == запись '$' удалена
preferences.applied == предпочтения применены
export.done == экспорт выполнен
import.done == импорт выполнен
password.changed == пароль изменен
modified.by == изменен пользователем
data.saved == данные сохранены
add.category.to.rootlevel == Добавить категорию в корневой уровень
add.entry.to.rootlevel == Добавить запись в корневой уровень
tabs.placement == Расположение закладок
icon == Иконка
caption == Заголовок
type == Тип
new.category == Новая категория
new.entry == Новая запись
add.category == добавить категорию
add.entry == добавить запись
no.entry.extensions.installed == На данный момент не установлено ни одного расширения-записи.<br/>Записи не могут быть добавлены до того, как по крайней мере одно расширение-запись будет установлено.
failed.to.add.category == Не удалось добавить категорию
failed.to.add.entry == Не удалось добавить запись.<br/>Некоторые расширения-записи возможно неисправны.<br/>Попробуйте открыть диалог управления расширениями, <br/>и удалить/переустановить неисправные расширения.
elapsed.time == прошло времени
estimated.time.left == осталось времени
transfer.type.no.longer.available == Похоже, что трансфер-тип используемый этой хранимой конфигурацией более не доступен (расширение удалено?)
wrong.password == Похоже, пароль не верный...
exporting.data == Экспортирую данные
data.export == Экспорт данных
export.completed == Экспорт данных - Завершен
export.success == Данные успешно экспортированы
export.failed == Не удалось экспортировать данные
export.failure == Экспорт данных - Неудача
export.discarded.no.data.changes == Экспорт отменен: данные не изменились со времени последнего экспорта
error.details == Детали ошибки
importing.data == Импортирую данные
data.import == Импорт данных
import.completed == Импорт данных - Завершен
import.success == Данные успешно импортированы
import.failed == Не удалось импортировать данные
import.failure == Импорт данных - Неудача
import.discarded.no.data.changes == Импорт отменен: данные не изменились со времени последнего импорта
change.password == изменить пароль
current.password == текущий пароль
new.password == новый пароль
new.password.confirmation == подтверждение нового пароля
change.password.failure == Не удалось изменить пароль!
change.password.failure.invalid.confirmation == Не удалось изменить пароль!<br/>Новый пароль не был корректно подтвержден!
change.password.success == Пароль успешно изменен