app.title == Bias :: Многофункциональный информационный менеджер
addons.management.title == Bias :: Управление Аддонами
version == Версия
username.preference.title == Имя пользователя
preferred.language.preference.title == Предпочитаемый язык (требует перезагрузки Bias)
preferred.datetime.format.preference.title == Предпочитаемый формат даты/времени
preferred.timeout.preference.title == Предпочитаемый таймаут для сетевых операций (в секундах)
use.systrayicon.preference.title == Использовать значок в системном лотке
use.systrayicon.preference.description == Резервирует место в системном лотке и разрешает прятать/восстанавливать приложение при помощи значка
remain.in.systray.on.window.close.preference.title == Оставаться в системном лотке при закрытии основного окна
start.hidden.preference.title == Прятать основное окно при старте
minimize.to.systray.preference.title == Сворачивать основное окно в системный лоток
auto.save.on.exit.preference.title == Автоматическое сохранение при выходе
display.confirmation.dialogs.preference.title == Показывать подтверждающие диалоги
display.confirmation.dialogs.preference.description == Запрашивает подтверждение пользователя при действиях наподобие удаления записи, деинсталляции расширения и т.п.
auto.mode.preference.title == Включить автоматический режим
auto.mode.preference.description == Разрешает выполнять некоторые простые действия (например, сохранение данных перед экспортом) в автоматическом режиме (без подтверждения пользователя)
enable.auto.update.preference.title == Разрешить автоматическое обновление (требует подключения к интернет)
auto.update.interval.preference.title == Интервал автоматического обновления, в днях (выставить на 0 для обновления только при старте)
show.memory.usage.preference.title == Показывать информацию о использовании памяти в строке состояния
export.info == Заметка: доступны два режима експорта:<br/><ul><li>статический - только выделенные елементы будут экпортированны</li><li>динамический - в дополнение к статически экспортируемым елементам, могут быть выбраны свернутые елементы (категории)<br/>для задействования динамического экспорта; в этом случае все вложенные елементы также будут экспортированны<br/>(это особенно удобно при использовании хранимых экспорт-конфигураций)</li></ul>
loaded.ready == загружен, готов к работе
category.added == категория '$' добавлена
entry.added == запись '$' добавлена
category.deleted == категория '$' удалена
entry.deleted == запись '$' удалена
preferences.applied == предпочтения применены
export.done == экспорт выполнен
import.done == импорт выполнен
password.changed == пароль изменен
modified.by == изменен пользователем
data.saved == данные сохранены
data.saving == сохранение данных...
error.message.data.collect.failure == Не удалось собрать данные!
error.message.toolsdata.collect.failure == Не удалось собрать данные инструментов!
error.message.data.save.failure == Не удалось сохранить данные!
add.category.to.rootlevel == Добавить категорию на корневой уровень
add.entry.to.rootlevel == Добавить запись на корневой уровень
tabs.placement == Расположение закладок
icon == Иконка
caption == Заголовок
type == Тип
add.category == Добавить категорию
add.entry == Добавить запись
configure.category == Настроить категорию
active.category.tabs.placement == Размещение закладок в активной категории
root.category.tabs.placement == Размещение закладок в корневой категории
category.configuration.error == Не удалось установить свойства категории!
entry.location == Размещение записи (будет перемещена при изменении)
configure.entry == Настроить запись
entry.configuration.error == Не удалось настроинть/применить/сохранить настройки записи!
relocate.entry.or.category == Переместить запись/категорию
relocate.failed == Не удалось переместить запись/категорию
no.entry.extensions.installed == На данный момент не установлено ни одного расширения-записи.<br/>Записи не могут быть добавлены до того, как по крайней мере одно расширение-запись будет установлено.
add.category.failure == Не удалось добавить категорию
add.entry.failure == Не удалось добавить запись.<br/>Некоторые расширения-записи возможно неисправны.<br/>Попробуйте открыть диалог управления расширениями, <br/>и удалить/переустановить неисправные расширения.
elapsed.time == прошло времени
estimated.time.left == осталось времени
transfer.type.no.longer.available == Похоже, что трансфер-тип используемый этой хранимой конфигурацией более не доступен (расширение удалено?)
wrong.password == Похоже, пароль неверный...
exporting.data == Экспортирую данные
data.export == Экспорт данных
export.completed == Экспорт данных - Завершен
export.success == Данные успешно экспортированы
export.failure == Не удалось экспортировать данные
error.details == Детали ошибки
importing.data == Импортирую данные
data.import == Импорт данных
import.completed == Импорт данных - Завершен
import.success == Данные успешно импортированы
import.failure == Не удалось импортировать данные
change.password == Изменить пароль
current.password == Текущий пароль
new.password == Новый пароль
password.confirmation == Подтверждение пароля
password.confirmation.failure == Пароль не был корректно подтвержден!
change.password.success == Пароль успешно изменен
change.password.failure == Не удалось изменить пароль!
delete.active.entry.or.category == Удалить текущую запись/категорию
delete.active.entry.or.category.failure == Не удалось удалить запись/категорию!
delete == Удалить
rename == Переименовать
save == Сохранить
new.name == Новое имя
overwrite.existing == Заменить существующие
update.installed == Обновить установленные
error == Ошибка
information == Информация
export.save.data.title == Сохранение данных перед экспортом
export.save.data.message == Данные должны быть сохранены перед экспортом. Сохранить сейчас и продолжить?
export.preferences == Экспорт предпочтений
export.data.entry.configs == Экспорт настроек записей
export.data.entry.configs.related.only == Экспортировать настройки только экспортируемых записей
export.tools.data == Экспорт данных инструментов
export.icons == Экспорт иконок
export.icons.related.only == Экспортировать иконки только экспортируемых записей
export.app.core == Экспорт ядра приложения
export.addons.and.libs == Экспорт расширений и библиотек
export.addon.configs == Экспорт настроек расширений
export.import.export.configs == Экспорт хранимых конфигураций импорта/экспорта
export.use.password == Зашифровать экспортируемые данные используя пароль
export.data.compressing == Упаковка данных для экспорта...
export.data.compressed == Данные для экспорта успешно упакованы
import.data.entries == Импорт записей
import.data.entry.configs == Импорт настроек записей
import.preferences == Импорт предпочтений
import.tools.data == Импорт данных инструментов
import.icons == Импорт иконок
import.and.update.app.core == Импорт и обновление ядра приложения
import.addons.and.libs == Импорт расширений и библиотек
import.addon.configs == Импорт настроек расширений
import.import.export.configs == Импорт хранимых конфигураций импорта/экспорта
import.use.password == Расшифровать импортируемые данные используя пароль
import.data.extracting == Распаковка данных для импорта...
import.data.extracted == Данные для импорта распакованы
import.failure.no.data.retrieved == Не удалось импортировать данные: данные не были получены!
import.data.retrieved == Данные для импорта получены
transfer.configuration.select == Выберите хранимую конфигурацию для использования, <br/>или оставьте поле для выбора пустым и нажмите ОК для начала настраиваемой траспортировки
transfer.type == Тип транспортировки
transfer.options.missing.error == Опции траспортировки не указаны!
transfer.file.location.missing.error == Месторасположение файла транспортировки не указано!
transfer.force == Транспортировать данные даже если они не изменились со времени последней транспортировки
transfer.data.transferring == Данные траспортируются...
transfer.configuration.delete.failure == Не удалось удалить выбранную транспортировочную конфигурацию!
transfer.configuration.rename.failure == Не удалось переименовать выбранную трансgортировочную конфигурацию!
transfer.configuration.save == Еслы вы желаете сохранить эту траспортировочную конфигурацию,<br/> введите имя для нее (или выберите уже существующее для замены)
transfer.configuration.saved == Траспортировочная конфигурация сохранена как '$'
transfer.discarded.no.data.changes == Транспортировка отменена: данные не изменились со времени последней траспортировки
password.confirmation.invalid == [НЕПОДТВЕРЖДЕНО]
password.confirmation.confirmed == [ПОДТВЕРЖДЕНО]
confirmation.delete.title == Подтверждение удаления
confirmation.delete.message == Вы действительно желаете удалить активный елемент?
confirmation.uninstall.title == Подтверждение удаления
confirmation.uninstall.message == Вы действительно желаете удалить выбранные расширения?
confirmation.disable.note == Заметка: этот диалог может быть отключен с помощью опции предпочтений<br/>
info.message.launcher.updated == Важно! Загрузчик Bias был обновлен.<br/>Однако, такое обновление не может быть применено автоматически.<br/>Для его применения, следует закрыть Bias, заменить файл <b><i>bias.jar<i></b> файлом <b><i>update_bias.jar<i></b> (в рабочей директории) и затем запустить Bias снова.
info.message.auto.update.complete == Автоматическое обновление выполнено
auto.update.disable.note == Заметка: автоматическое обновление может быть отключено<br/>при помощи опции предпочтений 'Разрешить автоматическое обновление'
auto.update.adjust.interval.note == Заметка: интервал автоматического обновления может быть настроен при помощи опции предпочтений 'Интервал автоматического обновления'
info.message.restart.to.apply.changes == Bias нужно перезагрузить для того, чтобы изменения были применены
info.message.entry.extension.first.usage == Это первый раз, когда вы используете расширение записи '$'.<br>Пожалуйста, выполните настройку расширения для использования по умолчанию...
error.message.extension.settings.serialization.failure == Расширение <i>$</i> потерпело неудачу при попытке сериализации настроек!<br/>Настройки, которые не удалось сохранить будут потеряны! :(<br/>Скорее всего, это ошибка расширения или проблема, связанная с зависимостями от библиотек сторонних разработчиков.<br/>Вы можете:<br/><ul><li>проверить не доступна ли новая версия расширения (ошибка может быть исправлена в новой версии)</li><li>проверить установлены ли все необходимые библиотеки сторонних разработчиков, от которых зависит расширение</li><li>удалить расширение во избежание подальшей нестабильности и потерь данных</li><li>связаться с разработчиком расширения для получения подальшей помощи</li></ul>
error.message.extension.data.serialization.failure == Расширение <i>$</i> потерпело неудачу при попытке сериализации данных!<br/>Настройки, которые не удалось сохранить будут потеряны! :(<br/>Скорее всего, это ошибка расширения или проблема, связанная с зависимостями от библиотек сторонних разработчиков.<br/>Вы можете:<br/><ul><li>проверить не доступна ли новая версия расширения (ошибка может быть исправлена в новой версии)</li><li>проверить установлены ли все необходимые библиотеки сторонних разработчиков, от которых зависит расширение</li><li>удалить расширение во избежание подальшей нестабильности и потерь данных</li><li>связаться с разработчиком расширения для получения подальшей помощи</li></ul>
error.message.tools.initialization.failure == Не удалось инициализировать инструменты!
error.message.tool.initialization.failure == Не удалось инициализировать расширение-инструмент '$'!
error.message.transferrers.initialization.failure == Не удалось инициализировать расширения-траспортеры!
error.message.transferrer.initialization.failure ==  Не удалось инициализировать расширение-траспортер '$'!
error.message.entryextension.initialization.failure == Не удалось инициализировать расширение-запись!
error.message.data.representation.failure == Обнаружена ошибка во время представления данных!
error.message.preferences.load.failure == Не удалось загрузить предпочтения!
error.message.preferences.save.failure == Не удалось сохранить предпочтения!
warning.message.preferences.contain.error == Предпочтения содержат ошибку(и)! Предпочтения не будут сохранены до тех пор, пока это не будет исправлено.
default.skin == Скин по умолчанию
default.skin.description == Нативный кросс-платформенный скин Java по умолчанию.
error.message.skin.initialization.failure == Не удалось инициализировать скин '$'!
info.message.extension.does.not.provide.detailed.info == Детальная информация не предоставляется данным расширением
error.message.extension.details.display.failure == Не удалось отобразить детали расширения!
info.message.skin.does.not.provide.detailed.info == Детальная информация не предоставляется данным скином
error.message.skin.details.display.failure == Не удалось отобразить детали скина!
info.message.iconset.does.not.provide.detailed.info == Детальная информация не предоставляется данным набором иконок
error.message.iconset.details.display.failure == Не удалось отобразить детали набора иконок!
info.message.library.does.not.provide.detailed.info == Детальная информация не предоставляется данной библиотекой
error.message.library.details.display.failure == Не удалось отобразить детали библиотеки!
error.message.invalid.url == Невалидный URL!
messages.history == История сообщений
choose.placement == Выберите размещение
info.message.entry.not.configurable == Выбранная запись не подлежит настройке!
info.message.entry.not.configurable.details == (соответствующее расширение не предоставляет опции настройки)
relocated.item == Элемент перемещения
target.category == Целевая категория
show.all.packages == Показывать все пакеты (включает в список уже установленные пакеты той же или более старой версии)
show.active.downloads == Показать активные загрузки
confirmation.cancel.active.downloads == Подтверждение отмены активных загрузок
confirmation.exit.unsaved.changes.message == Все несохраненные данные будут потеряны.
confirmation.exit == Вы уверены, что хотите завершить сеанс?
exit.confirmation == Подтверждение завершения сеанса
exit.confirmation.active.downloads.present == Присутствуют активные загрузки. Вы уверены, что хотите прервать их и выйти?
save.changes.before.exit == Сохранить данные перед выходом
exit == Выход
about.bias == О Bias
manage.addons == Управление расширениями
preferences == Предпочтения
add.or.install == Добавить/Установить
download.and.install == Загрузить/установить
install.or.update == Установить/Обновить
uninstall == Удалить
error.message.extensions.uninstall.failure == Не удалось удалить расширение(я)!
error.message.skins.uninstall.failure == Не удалось удалить скин(ы)!
error.message.iconsets.uninstall.failure == Не удалось удалить набор(ы) иконок!
error.message.icons.remove.failure == Не удалось удалить иконки!
error.message.icons.install.failure == Не удалось установить иконки!
remove.selected.icons == Удалить выделенные иконки
uninstall.selected.iconsets == Удалить выделенные наборы иконок
configure == Настроить
info.message.extension.is.not.yet.configurable == Данное расширение пока-что не может быть (пере)настроено.
reactivate.skin == (Ре)Активировать скин
info.message.skin.is.not.yet.activable == Данный скин пока-что не может быть активирован.
error.message.skin.reactivation.failure == Не удалось (ре)активировать скин!
info.message.restart.bias.first == Сперва перезагрузите Bias.
warning.message.nothing.to.install == Нечего устанавливать!
success.message.icons.installed == Иконки успешно установлены!
details == Детали
history.back.to.first == В самое начало
history.back == Назад
history.forward == Вперед
history.forward.to.last == В самый конец
running.tasks.wait == Некоторые задачи все еще выполняются, пожалуйста подождите пока они будут завершены...
running.tasks.force.exit == Принужденный выход (все незавершенные задачи будут прерваны)
error.data.load.failure == Не удалось загрузить данные!
memory.usage == Использование памяти: $ из $ Мб
info.message.icons.installation == установка иконок...
info.message.packages.installation == установка пакетов...
info.message.local.packages.installation == установка локальных пакетов...
error.message.dependency.resolution.failure == Не удалось разрешить зависимость пакета '$'! Следующий пакет-зависимость недоступен: $ '$' $.
error.message.dependencies.handle.resolve.failure == Не удалось обработать/разрешить зависимости!
version.x.or.higher == версия $ или выше
refresh == Обновить
error.message.pack.details.page.load.failure == Не удалось загрузить страницу деталей пакета!
error.message.repository.url.resolution.failure == Не удалось разрешить URL репозитория!
select.all.updates == Выделить все обновления
cancel.download.and.installation == Отменить загрузку/установку
filter == Фильтр
extensions == Расширения
skins == Скины
icons == Иконки
online == Онлайн
registered.libraries == Зарегистрированные библиотеки
clean.unused.data.and.config.files == Очистить неиспользуемые файлы данных и настроек
info.message.clean.unused.data.and.config.files == ЗАМЕТКА: Эта операция удалит все неиспользуемые файлы данных и настроек, которые использовались аддонами, которые сейчас не загружены<br>(Делайте это только если вы не планируете устанавливать эти аддоны снова или желаете сбросить их данные/настройки)
done == Готово
detect.unused.libraries == Обнаружить неиспользуемые библиотеки
uninstall.unused.libraries == Удалить неиспользуемые библиотеки!
info.message.uninstall.unused.libraries == ЗАМЕТКА: удаление неиспользуемых библиотек удалит все библиотеки, от которых зависели некоторые незагруженные сейчас аддоны<br>(Делайте это только если вы не планируете устанавливать эти аддоны снова)
error.message.unused.libraries.detection.failure == Не удалось обнаружить неиспользуемые библиотеки!
error.message.unused.libraries.uninstall.failure == Не удалось удалить неиспользуемые библиотеки!
advanced.options == Продвинутые опции
error.message.addons.management.screen.initialization.failure == Не удалось инициализировать экран управления аддонами!
error.message.addon.info.read.from.file.failure == Не удалось прочитать информацию расширения из файла
name == Название
version == Версия
author == Автор
description == Описание
status == Статус
type == Тип
size == Размер
info.message.refreshing.online.packages.list == обновление онлайн списка пакетов...
error.message.packages.list.parse.failure == Не удалось произвести разбор списка доступных пакетов!
error.message.packages.list.retrieve.failure == Не удалось загрузить список доступных аддонов!
info.message.packages.list.refresh.canceled.by.user == Обновление списка пакетов отменено пользователем!
info.message.downloading.and.installing.packages == загрузка/установка пакетов...
success.message.addon.installed == Аддон '$ $' был успешно установлен!
error.message.addon.installation.failure == Не удалось установить аддон '$ $'!
success.message.package.downloaded.and.installed == $ '$ $' - успешно загружено/установлено!
error.message.package.download.or.installation.failure == $ '$ $' - не удалось загрузить/установить!
error.message.failed.to.retrieve.package == Не удалось загрузить пакет!
info.message.package.download.and.installation.canceled.by.user == Загрузка/установка пакета '$ $' была отменена пользователем!
info.message.packages.download.and.installation.canceled.by.user == Загрузка/установка пакетов была отменена пользователем!
addons.installation.confirmation == Подтверждение установки аддонов
addon.dependencies == Зависимости аддона
addon.has.no.dependencies == Аддон не имеет зависимостей
applauncher == Загрузчик приложения
appcore == Ядро приложения
extension == Расширение
skin == Скин
iconset == Набор иконок
library == Библиотека