app.title == Bias :: Многофункциональный информационный менеджер
version == Версия
preferred.language.preference.title == Предпочитаемый язык (требует перезагрузки Bias)
preferred.datetime.format.preference.title == Предпочитаемый формат даты/времени
preferred.timeout.preference.title == Предпочитаемый таймаут для сетевых операций (в секундах)
use.systrayicon.preference.title == Использовать значок в системном лотке
use.systrayicon.preference.description == Резервирует место в системном лотке и разрешает прятать/восстанавливать приложение при помощи значка
remain.in.systray.on.window.close.preference.title == Оставаться в системном лотке при закрытии основного окна
start.hidden.preference.title == Прятать основное окно при старте
minimize.to.systray.preference.title == Сворачивать основное окно в системный лоток
auto.save.on.exit.preference.title == Автоматическое сохранение при выходе
display.confirmation.dialogs.preference.title == Показывать подтверждающие диалоги
display.confirmation.dialogs.preference.description == Запрашивает подтверждение пользователя при действиях наподобие удаления записи, деинсталляции расширения и т.п.
auto.mode.preference.title == Включить автоматический режим
auto.mode.preference.description == Разрешает выполнять некоторые простые действия (например, сохранение данных перед экспортом) в автоматическом режиме (без подтверждения пользователя)
enable.auto.update.preference.title == Разрешить автоматическое обновление (требует подключения к интернет)
auto.update.interval.preference.title == Интервал автоматического обновления, в днях (выставить на 0 для обновления только при старте)
show.memory.usage.preference.title == Показывать информацию о использовании памяти в строке состояния
export.info == Заметка: доступны два режима експорта:<br/><ul><li>статический - только выделенные елементы будут экпортированны</li><li>динамический - в дополнение к статически экспортируемым елементам, могут быть выбраны свернутые елементы (категории)<br/>для задействования динамического экспорта; в этом случае все вложенные елементы также будут экспортированны<br/>(это особенно удобно при использовании хранимых экспорт-конфигураций)</li></ul>
loaded.ready == загружен, готов к работе
category.added == категория '$' добавлена
entry.added == запись '$' добавлена
category.deleted == категория '$' удалена
entry.deleted == запись '$' удалена
preferences.applied == предпочтения применены
export.done == экспорт выполнен
import.done == импорт выполнен
password.changed == пароль изменен
modified.by == изменен пользователем
data.saved == данные сохранены
add.category.to.rootlevel == Добавить категорию в корневой уровень
add.entry.to.rootlevel == Добавить запись в корневой уровень
tabs.placement == Расположение закладок
icon == Иконка
caption == Заголовок
type == Тип
add.category == Добавить категорию
add.entry == Добавить запись
adjust.category == Отрегулировать категорию
adjust.entry == Отрегулировать запись
configure.entry == Настроить запись
no.entry.extensions.installed == На данный момент не установлено ни одного расширения-записи.<br/>Записи не могут быть добавлены до того, как по крайней мере одно расширение-запись будет установлено.
add.category.failure == Не удалось добавить категорию
add.entry.failure == Не удалось добавить запись.<br/>Некоторые расширения-записи возможно неисправны.<br/>Попробуйте открыть диалог управления расширениями, <br/>и удалить/переустановить неисправные расширения.
elapsed.time == прошло времени
estimated.time.left == осталось времени
transfer.type.no.longer.available == Похоже, что трансфер-тип используемый этой хранимой конфигурацией более не доступен (расширение удалено?)
wrong.password == Похоже, пароль неверный...
exporting.data == Экспортирую данные
data.export == Экспорт данных
export.completed == Экспорт данных - Завершен
export.success == Данные успешно экспортированы
export.failure == Не удалось экспортировать данные
error.details == Детали ошибки
importing.data == Импортирую данные
data.import == Импорт данных
import.completed == Импорт данных - Завершен
import.success == Данные успешно импортированы
import.failure == Не удалось импортировать данные
change.password == Изменить пароль
current.password == Текущий пароль
new.password == Новый пароль
password.confirmation == Подтверждение пароля
password.confirmation.failure == Пароль не был корректно подтвержден!
change.password.success == Пароль успешно изменен
change.password.failure == Не удалось изменить пароль!
delete.active.entry.or.category == Удалить текущую запись/категорию
delete.active.entry.or.category.failure == Не удалось удалить запись/категорию!
delete == Удалить
rename == Переименовать
save == Сохранить
new.name == Новое имя
overwrite.existing == Заменить существующие
update.installed == Обновить установленные
export.save.data.title == Сохранение данных перед экспортом
export.save.data.message == Данные должны быть сохранены перед экспортом. Сохранить сейчас и продолжить?
export.preferences == Экспорт предпочтений
export.data.entry.configs == Экспорт настроек записей
export.data.entry.configs.related.only == Экспортировать настройки только экспортируемых записей
export.tools.data == Экспорт данных инструментов
export.icons == Экспорт иконок
export.icons.related.only == Экспортировать иконки только экспортируемых записей
export.app.core == Экспорт ядра приложения
export.addons.and.libs == Экспорт расширений и библиотек
export.addon.configs == Экспорт настроек расширений
export.import.export.configs == Экспорт хранимых конфигураций импорта/экспорта
export.use.password == Зашифровать экспортируемые данные используя пароль
export.data.compressing == Упаковка данных для экспорта...
export.data.compressed == Данные для экспорта успешно упакованы
import.data.entries == Импорт записей
import.data.entry.configs == Импорт настроек записей
import.preferences == Импорт предпочтений
import.tools.data == Импорт данных инструментов
import.icons == Импорт иконок
import.and.update.app.core == Импорт и обновление ядра приложения
import.addons.and.libs == Импорт расширений и библиотек
import.addon.configs == Импорт настроек расширений
import.import.export.configs == Импорт хранимых конфигураций импорта/экспорта
import.use.password == Расшифровать импортируемые данные используя пароль
import.data.extracting == Распаковка данных для импорта...
import.data.extracted == Данные для импорта распакованы
import.failure.no.data.retrieved == Не удалось импортировать данные: данные не были получены!
import.data.retrieved == Данные для импорта получены
transfer.configuration.select == Выберите хранимую конфигурацию для использования, <br/>или оставьте поле для выбора пустым и нажмите ОК для начала настраиваемой траспортировки
transfer.type == Тип транспортировки
transfer.options.missing.error == Опции траспортировки не указаны!
transfer.file.location.missing.error == Месторасположение файла транспортировки не указано!
transfer.force == Транспортировать данные даже если они не изменились со времени последней транспортировки
transfer.data.transferring == Данные траспортируются...
transfer.configuration.delete.failure == Не удалось удалить выбранную трансортировочную конфигурацию!
transfer.configuration.rename.failure == Не удалось переименовать выбранную трансортировочную конфигурацию!
transfer.configuration.save == Еслы вы желаете сохранить эту траспортировочную конфигурацию,<br/> введите имя для нее (или выберите уже существующее для замены)
transfer.configuration.saved == Траспортировочная конфигурация сохранена как '$'
transfer.discarded.no.data.changes == Транспортировка отменена: данные не изменились со времени последней траспортировки
password.confirmation.invalid == [НЕПОДТВЕРЖДЕНО]
password.confirmation.confirmed == [ПОДТВЕРЖДЕНО]
confirmation.delete.title == Подтверждение удаления
confirmation.delete.message == Вы действительно желаете удалить активный елемент?
confirmation.uninstall.title == Подтверждение удаления
confirmation.uninstall.message == Вы действительно желаете удалить выбранные расширения?
confirmation.disable.note == Заметка: этот диалог может быть отключен с помощью опции предпочтений
info.message.launcher.updated == Важно! Загрузчик Bias был обновлен.<br/>Однако, такое обновление не может быть применено автоматически.<br/>Для его применения, следует закрыть Bias, заменить файл <b><i>bias.jar<i></b> файлом <b><i>update_bias.jar<i></b> (в рабочей директории) и затем запустить Bias снова.
exit == Выход
about == О Bias
manage.addons == Управление расширениями
preferences == Предпочтения
history.back.to.first == В самое начало
history.back == Назад
history.forward == Вперед
history.forward.to.last == В самый конец
running.tasks.wait == Некоторые задачи все еще выполняются, пожалуйста подождите пока они будут завершены...
running.tasks.force.exit == Принужденный выход (все незавершенные задачи будут прерваны)
memory.usage == Использование памяти: $ из $ Мб