//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.05.03 at 02:03:24 PM EEST 
//


package bias.extension.DashBoard.xmlb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for frameType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="frameType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Text-snippet"/>
 *     &lt;enumeration value="HTML-snippet"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum FrameType {

    @XmlEnumValue("Text-snippet")
    TEXT_SNIPPET("Text-snippet"),
    @XmlEnumValue("HTML-snippet")
    HTML_SNIPPET("HTML-snippet");
    private final String value;

    FrameType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FrameType fromValue(String v) {
        for (FrameType c: FrameType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
