//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.04.13 at 08:57:46 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://bias.sourceforge.net")
package bias.extension.DashBoard.xmlb;
